apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana
  namespace: monitoring
  labels:
    type: local
    id: grafana
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: /data/grafana
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path

