apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-server
  namespace: monitoring
  labels:
    type: local
    id: prometheus-server
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: /data/prometheus-server
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path

