---
# Source: prometheus/templates/server/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "server"
    app: prometheus
    release: prom-stack
    chart: prometheus-14.6.0
    heritage: Helm
  name: prom-stack-prometheus-server
  namespace: monitoring
  annotations:
    {}
