apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql
  namespace: database
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: /data
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path

