apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgreql
  namespace: database
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
